server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://kp45-mysql:3306/hello?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      filters: stat
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
  flyway:
    baseline-on-migrate: true
    clean-disabled: true
    locations: classpath:db/migrations
  redis:
    database: 0
    host: kp45-redis
    port: 6379
    lettuce:
      pool:
        max-active: 8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    io.kp45: info
  file: /tmp/app.log
  file.max-size: 50MB
  file.max-history: 10