version: "3"
services: 
  emqx-kuiper:
    image: emqx/kuiper:1.1.2-slim
    restart: always
    networks: 
      - docker-kp45
    environment: 
        - 'MQTT_SOURCE__DEFAULT__SERVERS=[tcp://broker.emqx.io:1883]'
  emqx-kuiper-manager:
    image: emqx/kuiper-manager:1.1.1
    ports:
      - 9082:9082
    networks: 
      - docker-kp45
  emqx-broker:
    image: emqx/emqx:latest
    restart: always
    ports:
      - 18083:18083
    networks: 
      - docker-kp45
networks:
  docker-kp45:
    driver: bridge