SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `hello`;
CREATE TABLE `hello` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`msg` varchar(255) NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;